# Makefile
# documents how to regenerate some .pngs
#
shoelaces-overview.png: shoelaces-overview.msc
	msc-gen \
		-T png \
		-i shoelaces-overview.msc \
		-o shoelaces-overview.png

#
# FYI  mscgen homepage is https://gitlab.com/msc-generator/msc-generator
# l l
