networkMaps:
  - network: 192.168.0.0/24
    script:
      name: ubuntu.ipxe
      params:
        release: jammy
  - network: 10.0.10.0/24
    script:
      name: flatcar.ipxe
      params:
        version: stable
hostnameMaps:
  - hostname: msc1.example.com
    script:
      name: debian.ipxe
      params:
        release: bookworm
