bind-addr=localhost:8081
data-dir=configs/data-dir/
template-extension=.slc
mappings-file=mappings.yaml
debug=true

[tftp]
enabled = true
address = ":69"
root = "/var/lib/shoelaces/tftp"
readonly = true
timeout_seconds = 5
